### PR TITLE
feat: add Home Assistant support

### PR DESCRIPTION
**Pull request by tomMoulard**

### CODE REVIEW

**Comment by tomMoulard** [comment]
@CodiumAI-Agent /Improve

**Comment by tomMoulard** [comment]
@CodiumAI-Agent /improve

**Comment by tomMoulard** [comment]
@CodiumAI-Agent /review

**Comment by ldez** [comment]
@CodiumAI-Agent /describe

**Comment by tomMoulard** [comment]
@CodiumAI-Agent /describe

**Comment by tomMoulard** [comment]
@CodiumAI-Agent /review -i

**Comment by tomMoulard** [comment]
@CodiumAI-Agent /improve

**Pull request merged**
